### ISSUE TITLE
forwarder content length 

### ISSUE THREAD

**Issue by yowenter** [jjyr/zerotest#10]
https://github.com/jjyr/zerotest/blob/master/zerotest/forwarder.py#L20
`        if not environ.get('CONTENT_LENGTH'):
            environ.pop('CONTENT_LENGTH', None)`

-- >
`        if  environ.has_key('CONTENT_LENGTH'):
            environ.pop('CONTENT_LENGTH', None)`

ps:  incorrect  content-length will make server stop iterate response body  . 
 [PEP3333](https://www.python.org/dev/peps/pep-3333/#handling-the-content-length-header)

**Comment by realityone** [comment]
Prefer to use `'CONTENT_LENGTH' in environ` is more pythonic, 
`has_key()` has been removed in python3+.

**Comment by jjyr** [comment]
The Werkzeug server will fill this header correct after return even the pre value is None, nothing need worry.
