### ISSUE TITLE
PEP8 - Code Consistency

### ISSUE THREAD

**Issue by TkTech** [jjyr/zerotest#3]
[PEP8](https://www.python.org/dev/peps/pep-0008/) is one of the strongest strengths of an open-source library - consistent, universal formatting.

Currently, very few files pass PEP8. There are 113 violations.

*Edit*: Additionally, it's typically considered a negative to litter your files with `__author__` and the likes. Especially if you're accepting contributions, this is needless maintenance and cruft. Just keep it in your `setup.py` and `zerotest/__ini__.py`.

**Comment by jjyr** [comment]
OK, I'll add contributors section to README and reference to github contributors graph.

**Comment by TkTech** [comment]
@jjyr This should be reopened, definitely not resolved. Still 107 PEP8 violations.
