### ISSUE TITLE
Assert being used for general comparisons

### ISSUE THREAD

**Issue by TkTech** [jjyr/zerotest#6]
`assert` is being used all over the place to ensure `l == r`. This is *bad* for multiple reasons, the biggest that all assert statements are turned into a `NOP` when running with optimizations.

Ex:
- https://github.com/jjyr/zerotest/blob/master/zerotest/response_matcher.py#L24
- https://github.com/jjyr/zerotest/blob/master/zerotest/response_matcher.py#L68
- https://github.com/jjyr/zerotest/blob/master/zerotest/response_matcher.py#L58

**Comment by jjyr** [comment]
The purpose of assert statement is test conditions during program run. In test context, any condition failed **should** be detected, use `-O` run testing and ignore assertion condition is totally wrong. Another reason is `pytest` display detail info of objects in assertion statement when test not pass, it helpful to fix code.
