### ISSUE TITLE
assert r1_content == r2_content 

### ISSUE THREAD

**Issue by allexeye** [jjyr/zerotest#9]
Is it possible to specify any conditions, that will allow me to test content that changes dynamically? F ex. if I have a timestamps in the response. Thanks!

**Comment by jjyr** [comment]
Currently you can just ignore specific fields with `--ignore-fields timestamp`, there are plans to provide more test conditions in future.

**Comment by allexeye** [comment]
is in py.test option?
```
vagrant@vagrant-ubuntu-vivid-64:/vagrant/zerotest$ py.test --ignore-fields servertime test_octocat.py
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --ignore-fields
  inifile: None
  rootdir: /vagrant/zerotest
```

**Comment by jjyr** [comment]
see `zerotest generate -h`
